// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vebpqwgvxbmxtcnuafgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlYnBxd2d2eGJteHRjbnVhZmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTY1OTQsImV4cCI6MjA1NzkzMjU5NH0.DAskJjLKwl4H30guZxdGIkeTsXDk2PQ8RMB0VddmvpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);